// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod"
import { makeRoute } from "./makeRoute"

const defaultInfo = {
  search: z.object({}),
}

import * as HomeRoute from "@/app/page.info"
import * as CollectionsRoute from "@/app/collections/page.info"
import * as CollectionRoute from "@/app/collections/[collectionName]/page.info"

export const Home = makeRoute("/", {
  ...defaultInfo,
  ...HomeRoute.Route,
})
export const Collections = makeRoute("/collections", {
  ...defaultInfo,
  ...CollectionsRoute.Route,
})
export const Collection = makeRoute("/collections/[collectionName]", {
  ...defaultInfo,
  ...CollectionRoute.Route,
})
